name: Release

on:
  release:
    types:
      - published

jobs:
  quality:
    name: Quality
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Setup latest Deno version
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x

      - name: Run Deno fmt
        run: deno fmt --check **.ts

      - name: Run Deno lint
        run: deno lint **.ts

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Setup latest Deno version
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x

      - name: Run Deno test
        run: deno test index.ts

  deploy:
    name: NPM publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Setup latest Deno version
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x

      - name: Setup Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Building package
        run: deno run --allow-run=npm --allow-net=deno.land --allow-env=HOME,DENO_AUTH_TOKENS,DENO_DIR,XDG_CACHE_HOME --allow-read --allow-write build.ts

      - name: Publishing to NPM
        run: cd dist && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}