name: Release

on:
  release:
    types:
      - published

jobs:
  quality:
    name: Quality
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup latest Deno version
        uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x

      - name: Check formatting with Deno
        run: deno task format:check

      - name: Check linting with Deno
        run: deno task lint

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup latest Deno version
        uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x

      - name: Run Deno test
        run: deno task test

  publish-npm:
    name: Publish NPM
    needs:
      - quality
      - test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup latest Deno version
        uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x

      - name: Setup Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: "latest"
          registry-url: "https://registry.npmjs.org"

      - name: Building package
        run: deno task build

      - name: Publishing to NPM
        run: cd npm && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-jsr:
    name: Publish JSR
    needs:
      - quality
      - test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Publishing to JSR
        run: npx jsr publish
