name: Release

on:
  release:
    types:
      - published

jobs:
  publish-npm:
    name: Publish NPM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup latest Deno version
        uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x

      - name: Setup Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: "latest"
          registry-url: "https://registry.npmjs.org"

      - name: Building package
        run: deno task build

      - name: Publishing to NPM
        run: cd npm && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-jsr:
    name: Publish JSR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup latest Deno version
        uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x

      - name: Publishing to JSR
        run: deno publish --token ${{ secrets.JSR_TOKEN }}
