name: Updates

on:
  workflow_dispatch:
    schedule:
      - cron: "00 00 * * *"

jobs:
  update:
    name: Updates
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Setup latest Deno version
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x

      - run: deno run -A https://deno.land/x/udd/main.ts **/*.ts
        name: Update dependencies

      - id: pr
        name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          body: Dependencies updated by [udd](https://github.com/hayd/deno-udd).
          title: Update dependencies
          branch: updates
          author: GitHub <noreply@github.com>
          delete-branch: true
          commit-message: "⬆️ Update dependencies"
    
      - id: commit
        run: echo "::set-output name=sha::$(git rev-parse HEAD)"
        name: Retrieve commit SHA

      - name: Set commit status with pending
        uses: Sibz/github-status-action@v1
        with: 
          sha: ${{ steps.commit.outputs.sha }}
          state: 'pending'
          context: 'Basic tests'
          authToken: ${{ secrets.GITHUB_TOKEN }}

      - id: test
        run: deno test index.ts
        name: Basic tests
        continue-on-error: true

      - name: Set commit status with outcome
        uses: Sibz/github-status-action@v1
        with: 
          sha: ${{ steps.commit.outputs.sha }}
          state: ${{ steps.test.outcome }}
          context: 'Basic tests'
          authToken: ${{ secrets.GITHUB_TOKEN }}
          description: 'To run other CI actions close/reopen this PR'